### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by fanyikoukouchi** [begeekmyfriend/leetcode#1]
int multiply(int a, char *b) { 
return a b; 
} 

我就想问这道算法题如何解，codewars 的 c 注册入门题目

**Comment by begeekmyfriend** [comment]
好刁钻啊，在周末提issue...帮你找到[参考](https://github.com/begeekmyfriend/leetcode/tree/master/043_multiply_strings)，剩下你应该知道怎么做
