### ISSUE TITLE
大神

### ISSUE THREAD

**Issue by xtxh** [begeekmyfriend/leetcode#3]
我是C小白，不知道每个case要做什么😂

**Comment by begeekmyfriend** [comment]
MakeFile懂不

**Comment by xtxh** [comment]
求教，Mac OS 10.13.3如何打开MakeFile文件呢😂

在 2018年2月27日，13:14，Leo Ma <notifications@github.com<mailto:notifications@github.com>> 写道：


MakeFile懂不

**Comment by begeekmyfriend** [comment]
```shell
cd 001
make
./test
```
