### ISSUE TITLE
0015 三数之和的函数定义处是 4 个参数，调用处是 3 个参数。

### ISSUE THREAD

**Issue by JasoonChen** [begeekmyfriend/leetcode#30]
如题。

**Comment by begeekmyfriend** [comment]
那是LeetCode的C语言题目的函数签名跟我最初提交有了变化，很多题目 **4年前**就是我这样的，当然有发现跟目前不一致的地方我会改过来

**Comment by begeekmyfriend** [comment]
那是LeetCode的C语言题目的函数签名跟我最初提交有了变化，很多题目 **4年前**就是我这样的，当然有发现跟目前不一致的地方我都会改过来的。
https://github.com/begeekmyfriend/leetcode/commit/4fab7e0a488ac63f4e5542952104467684e60614
