### ISSUE TITLE
小白关于代码格式的问题请教

### ISSUE THREAD

**Issue by yiran7324** [begeekmyfriend/leetcode#6]
如 [102](https://github.com/begeekmyfriend/leetcode/blob/master/102_binary_tree_level_order_traversal/bst_bfs.c) 中的 10 行和 16 行

在有参宏定义时 `#define` 后接空格数量，第 10 行为一个，换行接四个。第 16 行为八个，换行接八个。

这样写是遵循了哪种规范？

**Comment by begeekmyfriend** [comment]
嗯，可能在拷贝的时候发生一点问题，一般只要统一即可。
